### ISSUE TITLE
Polishing into a library

### ISSUE THREAD

**Issue by tedsta** [MeirBon/rfw-rs#4]
Hi! I think this project is super cool. I'm working on a game as a hobby with a friend of mine and have been putting together / using [this renderer](https://github.com/tedsta/wgpu-pbr). But I'd like to just drop that in favor of rfw-rs.

Do you intend to turn this into a library? I'd love to help out if you are open to it. I'm no graphics wizard but I can help with the docs / API / examples / performance side of things and can do a little bit of graphics (I think the repo I linked is a pretty accurate representation of my abilities graphics-wise).

**Comment by MeirBon** [comment]
Hey, thanks for reaching out. This project (and my previous similar C++ project) mostly served for me to put things I learned during my bachelor's and my (soon-to-be-graduated-from) masters into practice. My field of interest has mostly been into rendering techniques and optimization, but lately, I have been wanting to mess around with things like physics, proper animation support, and support for massive numbers of instances. My end goal is to be able to make a game with this framework as well.

The 'scene' crate already is a kind of library although I haven't actually published it (yet). Currently, I think the best bet for this framework is to implement an ECS kind of architecture. I have experience with this, but I haven't had much success with this project yet (all my attempts have been private till now, still looking into what libraries would be best to use). Feel free to come up with suggestions. Once an ECS-like architecture is established, it should be fairly easy to add any kind of functionality as you'd just add a new type component and implement the functionality as a system.

I am open to the idea of working together so if there is anything you'd like to do then feel free to discuss it, I would love to work on this project with others :smiley: 

Btw your project looked awesome as well, nice work!

**Comment by tedsta** [comment]
Cool! I was thinking a good place to warm up would be to turn the renderers into libraries and move the "cesium man" example scene into a separate example bin crate. Maybe even have it so you can dynamically switch between renderers using keyboard shortcuts?

For ECS, TBH it's what turned me off from Amethyst because it basically forces the game to also use ECS. Maybe if you could hide the ECS-ness so the game doesn't have to worry about the complex setup I would find it more palatable. I used to do everything game-related with ECS but nowadays I feel you can get the same benefits by just following the general ECS philosophy but not using an ECS framework - e.g. store "components" in `Vec`s and tie them together in custom game object structs that reference the components by ID. But I will follow your lead.

If there's an easier graphics feature you'd like but are uninterested in implementing feel free to delegate it to me and I'll probably be able to figure it out :smile: Like perhaps bloom for the deferred renderer?

**Comment by MeirBon** [comment]
Moving the renderers into libraries and creating examples sounds like a good idea. Switching between renderers would be awesome, but it's not possible yet. The renderers that have the most features are the GPU path tracer (gpu-rt) and the deferred renderer. They both use wgpu but they don't use the same data layouts. I think I'd be able to make them intercompatible, but it would be a bit of a hassle. I have been using the deferred renderer as my primary testing project and have been tempted to switch to Vulkan to have hardware RT support (I'm still hoping it becomes part of the webgpu standard haha).

About ECS, I fully agree with your sentiment. It's just that for some features that would mostly stay internal to an engine (e.g. physics), it does have some nice benefits. I am still not sure how to do it though, in the end it would be a flexible implementation (so no forced ECS like Amethyst).

Feel free to add things like bloom, small features are nice as well :) It's bedtime for me now so I'll give you access to the repo tomorrow.

Thank you for the complements :smile: I'm using a mobile RTX 2080 Max Q for that screenshot. Tbh I am not yet satisfied with the performance of that path tracer, but wgpu doesn't give me enough low-level access to certain things/I haven't discovered all the fast paths yet. My CUDA implementation in the C++ project is way faster even though I am using roughly the same code (just GLSL vs CUDA C++)

**Comment by tedsta** [comment]
Yeah it would be sweet if webgpu supports hardware RT in the future! Looks like somebody is working on it: https://github.com/maierfelix/dawn-ray-tracing

No need to give me access, I'll work through pull requests.

Cool I'll start with the library thing but make two separate examples, one for deferred and one for gpu-rt. Then give bloom a shot.

**Comment by tedsta** [comment]
I think we can close this open-ended issue and I'll file more specific issues?

**Comment by MeirBon** [comment]
Yes, sounds good.
